import { initQueryClient } from '@ts-rest/react-query';
import Head from 'next/head';
import Image from 'next/image';
import { PokemonCard } from '../components/PokemonCard';
import { pokemonApi } from '../pokeApi';
import styles from '../styles/Home.module.css';

export const queryClient = initQueryClient(pokemonApi, {
  baseUrl: 'https://pokeapi.co/api/v2',
  baseHeaders: {},
});

export default function Home() {
  const query = queryClient.getAllPokemon.useQuery(
    ['pokemon'],
    { query: { limit: 10 } },
    { staleTime: Infinity }
  );

  const pokemon = query.data?.status === 200 ? query.data.body : null;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Next.js with <a href="https://ts-rest.com">ts-rest!</a>
        </h1>

        <p className={styles.description}>
          Example of <code>@ts-rest/react-query</code> with the PokeAPI!
        </p>

        <div className={styles.grid}>
          {query.data?.body?.results.map((item) => (
            <div className={styles.card} key={item.url}>
              <h2>{item.name}</h2>
              <PokemonCard url={item.url} />
            </div>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
